### ISSUE TITLE
Unable to load BLK

### ISSUE THREAD

**Issue by FISHandCHEAP** [khang06/AssetStudio#1]
Hi,

I compiled your work and used GUI to load BLKs. I tried all BLKs but can load nothing. I use BLKs from v2.1.

**Comment by FISHandCHEAP** [comment]
"Show error message" box is checked, but nothing is shown after I load the file and only the bottom changed from "ready to go" to "no file was loaded".

**Comment by FISHandCHEAP** [comment]
YuanShen_Data\StreamingAssets\AssetBundles\blocks\00
I load BLKs from the above folder, is that correct?

**Comment by khang06** [comment]
yeah that looks about right. i'm not really sure what could be causing the issue here. just to verify that it isn't some weird build problem on your end, here's my local build of it: https://files.catbox.moe/9wvj35.7z

**Comment by FISHandCHEAP** [comment]
Your build works! I don't have C# environment so I asked other to compile, that may caused the problem, thanks. BTW, why not just put your build in the release?

**Comment by khang06** [comment]
never really got around to it since i don't think the code in this repo is good enough for that yet (or if it ever will be good enough for it)
