### ISSUE TITLE
Ignore type 'MesRendered' and 'SkinnedMeshRenderer'

### ISSUE THREAD

**Issue by Preciel** [khang06/AssetStudio#11]
Issue meant for @Razmoth (there is no issue tab on his repo)

When loading CAB/BKL, both 'MesRendered' and 'SkinnedMeshRenderer' type display error in console and consume a lot of RAM from time to time.

If they cannot be read anyway, it would be best to not try to load those types while loading assets.

![image](https://user-images.githubusercontent.com/15726325/158914410-493504ce-c882-499a-90cd-fe159f865906.png)

![image](https://user-images.githubusercontent.com/15726325/158914417-4790e2fd-853c-4759-97da-e5ccbbbd9d08.png)

![image](https://user-images.githubusercontent.com/15726325/158914424-7117b651-aa01-40e3-b191-5eb9df9b962e.png)

Bonus: Most users are most likely looking for the sprites, a filter to load only sprites would fasten the process.

**Comment by Razmoth** [comment]
Greetings.

sorry for the issue, i forgot to enable the `issues` tab after forking the repo.

regarding this specific issue, there has bee a "quick patch" that was supposed to fix loading renderers/models for 2.5.0, but that hot fix appear to break compatibility with older versions of the game.

hence, I'll roll back into the older implementation and leave a note that 2.5.0 models are not supported ATM, until it's REed and tested on multiple files.

**Comment by Preciel** [comment]
Thanks @Razmoth, I will ive it a try !

**Comment by Preciel** [comment]
closing
