### ISSUE TITLE
How do I download and use it

### ISSUE THREAD

**Issue by qingchunnh** [khang06/AssetStudio#5]
I searched for a long time and only found the original version of AssetStudio, but not your download address

**Comment by MrROBUST** [comment]
This repo doesn't contain builds to download, only source files. You can download builded version from this [forum post](https://zenhax.com/viewtopic.php?f=9&t=14172&sid=aeda3bf261217be767b03228835997d6&start=120#p65858), or build the project yourself.

**Comment by qingchunnh** [comment]
> This repo doesn't contain builds to download, only source files. You can download builded version from this [forum post](https://zenhax.com/viewtopic.php?f=9&t=14172&sid=aeda3bf261217be767b03228835997d6&start=120#p65858), or build the project yourself.

Thank you so much
